version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - LOG_LEVEL=debug
  patterns:
    build: .
    environment:
      - LOG_LEVEL=trace
    depends_on:
      - jaeger